List of mods
- Distant Horizons
- Reforged
- UnionLib
- Alloy Forgery
- Balm
- Default Skill Trees
- Fabric API
- Fabric language kotlin
- Immersive Aircraft
- Moving Elevators
- Mythic Metals
- OWO Lib
- Pufferfish Attributes
- Pufferfish Skills
- Silk
- Sodium
- Supermartijn642configlib
- Supermartijn642corelib
- Veinminer
- SVC
- Waystones
